export interface Product {
  id: string;
  thumbnail: string;
  title: string;
  category: string;
  mrp: number;
  description1?: string;
  description2?: string;
  review1?: string;
  review2?: string;
  person1?: string;
  person2?: string;
}

export const products: Product[] = [
  {
    id: "1",
    title: "Ready-Mix Concrete",
    category: "Concrete",
    thumbnail: "/products/Concrete/Ready-mix-concrete.jpg",
    mrp: 100,
    description1: "High-quality ready-mix concrete ideal for construction.",
    description2: "Perfect for foundations and large-scale projects.",
    review1: "Durable and easy to use. Highly recommend!",
    review2: "Worked perfectly for my home project.",
    person1: "Rajesh Singh",
    person2: "Meera Patel",
  },
  {
    id: "2",
    title: "Precast Concrete",
    category: "Concrete",
    thumbnail: "/products/Concrete/precast-concrete.jpg",
    mrp: 150,
    description1: "Precast concrete panels for easy and quick installation.",
    description2: "Ideal for building strong and stable structures.",
    review1: "Excellent product with great strength.",
    review2: "Time-saving and very durable.",
    person1: "Rohit Verma",
    person2: "Aarti Sharma",
  },
  {
    id: "3",
    title: "Reinforced Concrete",
    category: "Concrete",
    thumbnail: "/products/Concrete/reinforced-concrete.jpg",
    mrp: 200,
    description1: "Reinforced with steel for added durability.",
    description2: "Suitable for heavy-duty construction projects.",
    review1: "Best concrete for tough construction jobs.",
    review2: "Highly recommend for large-scale structures.",
    person1: "Karan Agarwal",
    person2: "Nisha Bhatia",
  },
  {
    id: "4",
    title: "High-Performance Concrete",
    category: "Concrete",
    thumbnail: "/products/Concrete/high-performance-concrete.png",
    mrp: 250,
    description1: "High-strength concrete for advanced building requirements.",
    description2: "Withstands extreme environmental conditions.",
    review1: "Perfect for high-rise buildings.",
    review2: "Unbeatable quality and strength.",
    person1: "Akshay Gupta",
    person2: "Priya Kumar",
  },

  // Masonry Products
  {
    id: "5",
    title: "Bricks",
    category: "Masonry",
    thumbnail: "/products/Masonry/bricks blocks.jpg",
    mrp: 50,
    description1: "Premium quality bricks for long-lasting structures.",
    description2: "Perfect for both commercial and residential projects.",
    review1: "Very solid bricks at a reasonable price.",
    review2: "Used them for my house construction, very satisfied.",
    person1: "Arjun Desai",
    person2: "Sneha Kapoor",
  },
  {
    id: "6",
    title: "Masonry Tools Set",
    category: "Masonry",
    thumbnail: "/products/Masonry/Masnory-toolset.png",
    mrp: 500,
    description1: "Complete set of masonry tools for any project.",
    description2: "Includes trowels, mixers, and more.",
    review1: "Great value for the price, has everything you need.",
    review2: "Tools are sturdy and easy to handle.",
    person1: "Suresh Rao",
    person2: "Pooja Jain",
  },

  // Wood Products
  {
    id: "7",
    title: "Plywood Sheets",
    category: "Wood",
    thumbnail: "/products/wood/plywood-sheets.png",
    mrp: 600,
    description1: "High-quality plywood for construction and furniture.",
    description2: "Ideal for interior and exterior use.",
    review1: "Strong and reliable, perfect for my DIY projects.",
    review2: "The best plywood I've used, would buy again.",
    person1: "Amit Joshi",
    person2: "Neha Mehta",
  },
  {
    id: "8",
    title: "Lumber Beams",
    category: "Wood",
    thumbnail: "/products/wood/Lumber-Beams.png",
    mrp: 800,
    description1: "Sturdy lumber beams for structural support.",
    description2: "Perfect for framing and large construction.",
    review1: "High-quality beams, very sturdy.",
    review2: "Exactly what I needed for my construction project.",
    person1: "Anil Yadav",
    person2: "Reena Nair",
  },
  {
    id: "9",
    title: "Wooden Planks",
    category: "Wood",
    thumbnail: "/products/wood/wooden-planks.jpg",
    mrp: 400,
    description1: "Durable wooden planks for various uses.",
    description2: "Great for flooring, decking, and construction.",
    review1: "Smooth finish and durable, excellent quality.",
    review2: "These planks are perfect for my deck.",
    person1: "Rakesh Malhotra",
    person2: "Kavita Iyer",
  },

  // Metals Products
  {
    id: "10",
    title: "Steel Rebars",
    category: "Metals",
    thumbnail: "/products/Metals/steel-rebars.png",
    mrp: 1000,
    description1: "Steel rebars for reinforcing concrete structures.",
    description2: "Essential for any large construction project.",
    review1: "Very strong and durable, a must-have for solid construction.",
    review2: "Top quality, no complaints.",
    person1: "Mohan Tripathi",
    person2: "Priyanka Sen",
  },
  {
    id: "11",
    title: "Aluminum Sheets",
    category: "Metals",
    thumbnail: "/products/Metals/aluminium-sheets.png",
    mrp: 700,
    description1: "Lightweight aluminum sheets for versatile use.",
    description2: "Great for roofing, siding, and fabrication.",
    review1: "Super lightweight yet strong.",
    review2: "Perfect for roofing my shed.",
    person1: "Gaurav Khanna",
    person2: "Sandhya Dixit",
  },
  {
    id: "12",
    title: "Metal Pipes",
    category: "Metals",
    thumbnail: "/products/Metals/metal-pipes.jpg",
    mrp: 500,
    description1: "Heavy-duty metal pipes for plumbing and construction.",
    description2: "Durable and rust-resistant.",
    review1: "Pipes are solid, no leaks at all.",
    review2: "Good quality, worked perfectly for my project.",
    person1: "Aniket Ghosh",
    person2: "Suman Chakraborty",
  },

  // Roofing Products
  {
    id: "13",
    title: "Roofing Shingles",
    category: "Roofing",
    thumbnail: "/products/Roofing/roofing-shingles.png",
    mrp: 300,
    description1: "Asphalt roofing shingles for durable roofing.",
    description2: "Ideal for residential homes.",
    review1: "Great quality shingles, very durable.",
    review2: "Easy to install and long-lasting.",
    person1: "Aditya Sinha",
    person2: "Lakshmi Rao",
  },
  {
    id: "14",
    title: "Metal Roofing Sheets",
    category: "Roofing",
    thumbnail: "/products/Roofing/metal-roffingsheets.png",
    mrp: 800,
    description1: "Corrugated metal roofing sheets for weather resistance.",
    description2: "Perfect for industrial and residential buildings.",
    review1: "Very sturdy, perfect for my warehouse.",
    review2: "Weatherproof and easy to install.",
    person1: "Rajeev Nair",
    person2: "Sunita Patel",
  },
  {
    id: "15",
    title: "Roofing Nails",
    category: "Roofing",
    thumbnail: "/products/Roofing/roofing-nails.png",
    mrp: 50,
    description1: "Galvanized roofing nails for secure installation.",
    description2: "Corrosion-resistant for long-lasting hold.",
    review1: "These nails are tough and reliable.",
    review2: "Perfect for my roofing job, held up well.",
    person1: "Vikas Saxena",
    person2: "Swati Gupta",
  },

  // Insulation Products
  {
    id: "16",
    title: "Fiberglass Insulation",
    category: "Insulation",
    thumbnail: "/products/Insulation/Fibreglass-Insulation.png",
    mrp: 400,
    description1: "High-efficiency fiberglass insulation for thermal control.",
    description2: "Ideal for walls and attics.",
    review1: "Great insulation, easy to install.",
    review2: "Keeps my house warm and quiet.",
    person1: "Rahul Shetty",
    person2: "Deepa Menon",
  },
  {
    id: "17",
    title: "Foam Board Insulation",
    category: "Insulation",
    thumbnail: "/products/Insulation/FoamBoard.png",
    mrp: 600,
    description1: "Durable foam board insulation for high-performance.",
    description2: "Lightweight and moisture-resistant.",
    review1: "Perfect for insulating my garage.",
    review2: "Easy to cut and install, great product.",
    person1: "Ramesh Singh",
    person2: "Tara Sharma",
  },

  // Flooring Products
  {
    id: "18",
    title: "Ceramic Tiles",
    category: "Flooring",
    thumbnail: "/products/Flooring/ceramic-tiles.jpg",
    mrp: 200,
    description1: "Ceramic tiles for elegant and durable flooring.",
    description2: "Scratch-resistant and easy to clean.",
    review1: "Beautiful finish and very durable.",
    review2: "Perfect for my kitchen floor.",
    person1: "Sunil Verma",
    person2: "Priya Iyer",
  },
  {
    id: "19",
    title: "Laminate Flooring",
    category: "Flooring",
    thumbnail: "/products/Flooring/laminate.png",
    mrp: 500,
    description1: "Laminate flooring with a wood-like finish.",
    description2: "Affordable and easy to install.",
    review1: "Looks just like real wood, amazing!",
    review2: "Very durable and easy to clean.",
    person1: "Amit Rao",
    person2: "Nina Gupta",
  },
  {
    id: "20",
    title: "Vinyl Flooring",
    category: "Flooring",
    thumbnail: "/products/Flooring/vinyl-flooring.jpg",
    mrp: 300,
    description1: "Vinyl flooring for water-resistant durability.",
    description2: "Ideal for kitchens and bathrooms.",
    review1: "Looks great and very easy to maintain.",
    review2: "Perfect for my bathroom, very happy with the result.",
    person1: "Vikram Yadav",
    person2: "Nisha Sharma",
  },

  // Plumbing Products
  {
    id: "21",
    title: "PVC Pipes",
    category: "Plumbing",
    thumbnail: "/products/Plumbing/pvc-pipes.jpg",
    mrp: 150,
    description1: "Durable PVC pipes for plumbing needs.",
    description2: "Rust-resistant and long-lasting.",
    review1: "Great for my plumbing project.",
    review2: "Solid pipes, easy to install.",
    person1: "Rajesh Kumar",
    person2: "Leela Mehta",
  },
  {
    id: "22",
    title: "Faucets",
    category: "Plumbing",
    thumbnail: "/products/Plumbing/faucets.jpg",
    mrp: 800,
    description1: "High-quality faucets with chrome finish.",
    description2: "Durable and easy to install.",
    review1: "Looks elegant and works perfectly.",
    review2: "Top-notch quality, highly recommend.",
    person1: "Anil Gupta",
    person2: "Suman Yadav",
  },
];
////////////////////////////
export const categories = [
  {
    id: "0",
    category: "All",
    thumbnail: "/products/all.jpg",
  },
  {
    id: "1",
    category: "Concrete",
    thumbnail: "/products/Concrete/precast-concrete.jpg",
  },
  {
    id: "2",
    category: "Masonry",
    thumbnail: "/products/Masonry/cement.jpg",
  },
  {
    id: "3",
    category: "Wood",
    thumbnail: "/products/wood/Lumber-Beams.png",
  },
  {
    id: "4",
    category: "Metals",
    thumbnail: "/products/Metals/steel-rebars.png",
  },
  {
    id: "5",
    category: "Roofing",
    thumbnail: "/products/Roofing/roof-top.jpg",
  },
  {
    id: "6",
    category: "Insulation",
    thumbnail: "/products/Insulation/FoamBoard.png",
  },
  {
    id: "7",
    category: "Flooring",
    thumbnail: "/products/Flooring/ceramic-tiles.jpg",
  },
  {
    id: "8",
    category: "Plumbing",
    thumbnail: "/products/Plumbing/pvc-pipes.jpg",
  },
];
